// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9D52X4knXYj--Aqz4V4jH-FVqoxok80',
    appId: '1:1047493940995:web:9beec446c3e93533d7bb36',
    messagingSenderId: '1047493940995',
    projectId: 'movie-app-5fbaf',
    authDomain: 'movie-app-5fbaf.firebaseapp.com',
    storageBucket: 'movie-app-5fbaf.appspot.com',
    measurementId: 'G-ZMEY60ZMWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-kMX_xBsPi1mHubEL8vXSMcBDMmPPT8',
    appId: '1:1047493940995:android:a0f5be3ee43060afd7bb36',
    messagingSenderId: '1047493940995',
    projectId: 'movie-app-5fbaf',
    storageBucket: 'movie-app-5fbaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIS4ay1fN8WPOaept40JQvMDmX7ggWMV8',
    appId: '1:1047493940995:ios:9f0f764939483b94d7bb36',
    messagingSenderId: '1047493940995',
    projectId: 'movie-app-5fbaf',
    storageBucket: 'movie-app-5fbaf.appspot.com',
    iosClientId: '1047493940995-bfev9mr0b658jeb6fsan7q9nojjgtoqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIS4ay1fN8WPOaept40JQvMDmX7ggWMV8',
    appId: '1:1047493940995:ios:e570505c0500b259d7bb36',
    messagingSenderId: '1047493940995',
    projectId: 'movie-app-5fbaf',
    storageBucket: 'movie-app-5fbaf.appspot.com',
    iosClientId: '1047493940995-dfa6udsomf35nbbvsl561p55qu9osf4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
